import React, { useState } from 'react';
import Navbar from './Navbar';
import Footer from './Footer';
import Head from 'next/head';
import { useTheme } from 'next-themes';

const Layout = ({ children }) => {
  const { theme, setTheme } = useTheme();

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className='bg-gradient-to-b from-stone-200 dark:from-darkBgTop'>
        <Navbar />
        <button
          className='bg-gray'
          onClick={() => setTheme(theme === 'dark' ? 'light' : 'dark')}
        >
          Toggle
        </button>
        <section className='min-h-screen font-Roboto flex flex-col'>
          {children}
        </section>
        <Footer />
      </main>
    </>
  );
};

export default Layout;
